name: Upstream Dispatch
on: repository_dispatch
permissions: read-all
jobs:
  build:
    name: ${{ github.event.client_payload.message }}
    runs-on: ubuntu-latest
    env:
      ASCIIDOCTOR_DIAGRAM_VERSION: '~> 2.1'
      PYGMENTS_VERSION: '~> 2.0'
      RGHOST_VERSION: '0.9.7'
      PRAWN_GMAGICK_VERSION: '0.0.9'
    steps:
    - uses: actions/checkout@v3
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - name: Configure Bundler
      run: |
        bundle config --local clean true
        bundle config --local path .bundle/gems
        bundle config --local without coverage docs lint
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ghostscript libgraphicsmagick1-dev poppler-utils
    - name: Install dependencies
      run: |
        bundle --jobs 3 --retry 3
        bundle exec ruby scripts/switch-to-asciidoctor-head.rb ${{ github.event.client_payload.branch }}
        rm -f Gemfile.lock
        bundle --jobs 3 --retry 3
    - name: Run tests
      run: bundle exec ruby -w $(bundle exec ruby -e 'print File.join Gem.bindir, %q(rake)') spec
